module.exports = [
	'./bower/jquery/dist/jquery.js',
	'./bower/smooth-scroll/dist/js/smooth-scroll.js',
	'./bower/fancybox/source/jquery.fancybox.js',
	'./bower/fancybox/source/helpers/jquery.fancybox-media.js',
	// './bower/bootstrap-sass/assets/javascripts/bootstrap.js',
	'./bower/bootstrap-sass/assets/javascripts/bootstrap/transition.js',
	'./bower/bootstrap-sass/assets/javascripts/bootstrap/alert.js',
	'./bower/bootstrap-sass/assets/javascripts/bootstrap/button.js',
	'./bower/bootstrap-sass/assets/javascripts/bootstrap/carousel.js',
	'./bower/bootstrap-sass/assets/javascripts/bootstrap/collapse.js',
	'./bower/bootstrap-sass/assets/javascripts/bootstrap/dropdown.js',
	'./bower/bootstrap-sass/assets/javascripts/bootstrap/modal.js',
	'./bower/bootstrap-sass/assets/javascripts/bootstrap/tooltip.js',
	'./bower/bootstrap-sass/assets/javascripts/bootstrap/popover.js',
	'./bower/bootstrap-sass/assets/javascripts/bootstrap/scrollspy.js',
	'./bower/bootstrap-sass/assets/javascripts/bootstrap/tab.js',
	'./bower/bootstrap-sass/assets/javascripts/bootstrap/affix.js',
	'./src/js/modules/jquery.mousewheel.js',
	'./src/js/modules/mwheelIntent.js',
	'./src/js/modules/jquery.jscrollpane.js',
	'./src/js/modules/skrollr.js',
	'./src/js/modules/journee.js'
];
